"""new attendance module

Revision ID: 007d249c9821
Revises: 5295541cccf6
Create Date: 2025-03-18 22:06:03.702724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007d249c9821'
down_revision: Union[str, None] = '5295541cccf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry_exit_times', sa.Column('overlapping_classes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry_exit_times', 'overlapping_classes')
    # ### end Alembic commands ###
