"""removed valid students

Revision ID: 3654803bdb24
Revises: a2c1baa23047
Create Date: 2025-04-06 18:11:53.438017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3654803bdb24'
down_revision: Union[str, None] = 'a2c1baa23047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('students_roll_number_fkey', 'students', type_='foreignkey')
    op.drop_table('valid_students')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('students_roll_number_fkey', 'students', 'valid_students', ['roll_number'], ['roll_number'])
    op.create_table('valid_students',
    sa.Column('roll_number', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('roll_number', name='valid_students_pkey'),
    sa.UniqueConstraint('email', name='valid_students_email_key')
    )
    # ### end Alembic commands ###
