"""DSU update

Revision ID: 3acf44d0db56
Revises: 696346c30b10
Create Date: 2025-03-28 14:20:44.362752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3acf44d0db56'
down_revision: Union[str, None] = '696346c30b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dynamic_schedule_updates', sa.Column('original_date', sa.Date(), nullable=True))
    op.add_column('dynamic_schedule_updates', sa.Column('new_date', sa.Date(), nullable=True))
    op.alter_column('dynamic_schedule_updates', 'schedule_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('dynamic_schedule_updates', 'new_day_of_week')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dynamic_schedule_updates', sa.Column('new_day_of_week', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.alter_column('dynamic_schedule_updates', 'schedule_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('dynamic_schedule_updates', 'new_date')
    op.drop_column('dynamic_schedule_updates', 'original_date')
    # ### end Alembic commands ###
