"""forgot password

Revision ID: 696346c30b10
Revises: 9cba97ebc276
Create Date: 2025-03-26 00:43:57.343850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '696346c30b10'
down_revision: Union[str, None] = '9cba97ebc276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_verifications', sa.Column('purpose', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_verifications', 'purpose')
    # ### end Alembic commands ###
